# tasks for configuring the backend DB for Airflow

- name: get airflow info
  set_fact:
    airflow_chart: "{{ charts|selectattr('name', '==', 'airflow')| first }}"

### we collect the admin password of Postgres
- name: get postgres admin password
  shell: 
    cmd: echo $(kubectl get secret postgres-admin -n {{ platform_id }}-data -o json | jq -r .data)
  register: postgres_admin_password
  environment:
    KUBECONFIG : "{{ kubeconfig_path }}"

- name: extract password - 1
  set_fact:
    postgres_admin_password: "{{ postgres_admin_password.stdout| from_json }}"

- name: extract password - 2
  set_fact:
    postgres_admin_password: "{{ postgres_admin_password['postgres-password'] | b64decode }}"

### we collect the password of the Airflow DB of Postgres
- name: get postgres airflow DB admin password
  shell: 
    cmd: echo $(kubectl get secret {{ airflow_chart.config.externalDatabase.existingSecret }} -n {{ platform_id }}-compute -o json | jq -r .data)
  register: airflow_db_admin_password
  environment:
    KUBECONFIG : "{{ kubeconfig_path }}"

- name: extract password - 1
  set_fact:
    airflow_db_admin_password: "{{ airflow_db_admin_password.stdout| from_json }}"

- name: extract password - 2
  set_fact:
    airflow_db_admin_password: "{{ airflow_db_admin_password['password'] | b64decode }}"

### configuration of the Airflow DB
- name: Purge airflow database if exists
  community.postgresql.postgresql_db:
    login_host: "{{ proxy_address }}"
    login_user: postgres
    # login_user: admin
    login_password: "{{ postgres_admin_password }}"
    port: "{{ external_postgres_port }}"
    name: "{{ airflow_chart.config.externalDatabase.database }}"
    state: absent
  when: purge_airflow_data

- name: Connect to postgres DB, create airflow user, and grant access to database and products table
  community.postgresql.postgresql_user:
    login_host: "{{ proxy_address }}"
    # login_user: admin
    login_user: postgres
    login_password: "{{ postgres_admin_password }}"
    port: "{{ external_postgres_port }}"
    name: "{{ airflow_chart.config.externalDatabase.user }}"
    password: "{{ airflow_db_admin_password }}"

- name: Create a new database with name airflow
  community.postgresql.postgresql_db:
    login_host: "{{ proxy_address }}"
    login_user: postgres
    # login_user: admin
    login_password: "{{ postgres_admin_password }}"
    port: "{{ external_postgres_port }}"
    name: "{{ airflow_chart.config.externalDatabase.database }}"
    owner: "{{ airflow_chart.config.externalDatabase.user }}"