# tasks for managing docker repo kubernetes secrets

- name: delete docker repo secrets if exist
  shell: "kubectl delete secret {{ item.name }} -n {{ item.namespace }} --ignore-not-found"
  environment:
    KUBECONFIG : "{{ kubeconfig_path }}"

- name: create docker repo secret
  shell: "kubectl create secret docker-registry {{ item.name }} -n {{ item.namespace }} --docker-server={{ item.repo }} --docker-username={{ item.username }} --docker-password={{ item.password }}"
  environment:
    KUBECONFIG : "{{ kubeconfig_path }}"