# tasks for managing kubernetes secrets used by deployments
- debug:
    msg: Creating secret {{ item.name }} in namespace {{ item.namespace }}

- name: delete the k8s secret if exists
  shell: "kubectl delete secret {{ item.name }} -n {{ item.namespace }} --ignore-not-found"
  environment:
    KUBECONFIG : "{{ kubeconfig_path }}"
  args:
    chdir: "{{ workdir }}"

- name: create secret string
  set_fact:
    k8s_string_secret: |-
      {% for cont in item.content %} --from-literal={{ cont.key }}={{ cont.value }}{% endfor %}

- name: create namespace if not exists
  shell: kubectl get ns | grep -q '^{{ item.namespace }}' || kubectl create ns {{ item.namespace }}
  environment:
    KUBECONFIG : "{{ kubeconfig_path }}"
  args:
    chdir: "{{ workdir }}"

- name: create k8s secret
  shell: "kubectl create secret generic {{ item.name }} -n {{ item.namespace }} {{ k8s_string_secret }}"
  environment:
    KUBECONFIG : "{{ kubeconfig_path }}"
  args:
    chdir: "{{ workdir }}"
