# tasks for managing kubernetes secrets used by deployments
- debug:
    msg: Creating secret {{ item.name }} in namespace {{ item.namespace }}

- name: delete the k8s secret if exists
  shell: "kubectl delete secret {{ item.name }} -n {{ item.namespace }} --ignore-not-found"
  environment:
    KUBECONFIG : "{{ kubeconfig_path }}"

- name: create secret string
  set_fact:
    k8s_string_secret: |
      {% for k,v in item.content %}
      - '--from-file='{{ v }}
      {% endfor %}

- name: create secret string - II
  set_fact:
    k8s_string_secret: "{{ ' '.join(k8s_string_secret) }}"

- name: create k8s secret
  shell: "kubectl create secret generic {{ item.name }} -n {{ item.namespace }} {{ k8s_string_secret }}"
  environment:
    KUBECONFIG : "{{ kubeconfig_path }}"
