---
- name: update hostname according to inventory file
  hosts: "{{ hosts }}"
  gather_facts: yes
  become: yes
  become_method: sudo
  tasks:
    - name: update hostname to inventory hostname
      shell: hostnamectl set-hostname {{ vm_names[inventory_hostname] | default(inventory_hostname)}}
    - name: make sure the hostname change is permanent
      replace:
        path: '/etc/cloud/cloud.cfg'
        regexp: 'preserve_hostname: false'
        replace: 'preserve_hostname: true'
      ignores_errors: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'