- name: "Wait ssh"
  hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  tags: [always]
  tasks:
    - name: Wait 300 seconds that ssh -> available
      ansible.builtin.wait_for_connection:
        timeout: 600
