modules:
- id: base
  name: Base
- id: databases
  name: Databases
- id: dataflow
  name: Dataflow
- id: monitoring
  name: Monitoring and Synchronization
- id: high_memory
  name: High Memory Stack
- id: compute
  name: Spark Compute Stack
- id: lab
  name: Machine Learning Lab
- id: ci
  name: Dev CI Stack
- id: front
  name: Frontend Stack
components:
- name: Longhorn
    version: 1.5.1
    id: longhorn
    module: base
  - name: Kubeapps
    version: 14.0.2
    id: kubeapps
    module: monitoring
  - name: Prometheus
    version: 8.21.6
    id: prometheus
    module: monitoring
  - name: Ingress Nginx
    version: 4.8.2
    id: nginx
    module: base
  - name: MongoDB
    version: 6.0.5
    id: mongodb
    module: databases
  - name: ElasticSearch
    version: 8.7.0
    id: elasticsearch
    module: databases
  - name: PostgreSQL
    version: 15.2.0
    id: postgresql
    module: databases
  - name: Redis
    version: 7.0.11
    id: redis
    module: databases
  - name: Kibana
    version: 8.7.0
    id: front
    module: base
  - name: Kafka
    version: 3.4.0
    id: kafka
    module: dataflow
  - name: Spark
    version: 3.3.2
    id: spark
    module: compute
  - name: Jupyterhub
    version: 4.0.2
    id: jupyterhub
    module: lab
  - name: ArgoCD
    version: 2.6.7
    id: argocd
    module: monitoring
  - name: KeyCloak
    version: 21.0.2
    id: keycloak
    module: base
  - name: Airflow
    version: 2.6.1
    id: airflow
    module: compute
  - name: Grafana
    version: 9.4.7
    id: grafana
    module: monitoring
  - name: Appsmith
    version: v1.9.31
    id: appsmith
    module: front
    default: false
  - name: Oathkeeper
    version: v0.40.6
    id: oathkeeper
    module: base